version : "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    init : true
    volumes:
      - ./Backend:/app
      - /app/node_modules


  ngnix:
    build:
      context: .
      dockerfile: ngnix.Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend