
services:
  backend:
    image: vivekdudi/xconnect-backend:latest
    restart: always
    init : true
    env_file:
      - .env
    ports:
      - "44400-44500:44400-44500/udp"
    volumes:
      - /home/ubuntu/xconnect/uploads:/app/uploads
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg:ro



  nginx:
    image: vivekdudi/xconnect-nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro


    