name: Backend CI/CD

on:
  push:
    branches: [ master ]
    
  # workflow dispatch allows to enable button for running pipeline the workflow from the GitHub Actions on web.    
  workflow_dispatch:
    inputs:
      reason:
        description: 'manually test to find inconsistencies'
        required: false
        default: 'Manual Trigger'

concurrency:
  group: 'Backend CI/CD'
  cancel-in-progress: false         

jobs:
  test:

    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: Backend
        
    env:
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_SECRET_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_SECRET_EXPIRES_IN }}
      REFRESH_TOKEN_SECRET_EXPIRES_IN: ${{ secrets.REFRESH_TOKEN_SECRET_EXPIRES_IN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_VIDEO_BUCKET: ${{ secrets.SUPABASE_VIDEO_BUCKET }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      PORT: ${{secrets.PORT}}
      BACKEND_URL: ${{secrets.BACKEND_URL}}
      CLIENT_URL: ${{secrets.CLIENT_URL}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      PUBLISHABLE_STRIPE_KEY: ${{secrets.PUBLISHABLE_STRIPE_KEY}}
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      WEBHOOK_KEY: ${{secrets.WEBHOOK_KEY}}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: Backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --coverage --detectOpenHandles --forceExit


  build-deploy:
    needs: test
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      

      - name: Build & Push Nod.js Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./Backend
          file: ./Backend/node.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/xconnect-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/xconnect-backend:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Build & Push nginx Docker Image
        uses: docker/build-push-action@v7
        with: 
          context: .
          file: nginx.prod.Dockerfile
          push: true
          build-args: |
            VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
            VITE_PRODUCTION_URL=${{ secrets.VITE_PRODUCTION_URL }}
            VITE_DEVELOPMENT_URL=${{ secrets.VITE_DEVELOPMENT_URL }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/xconnect-nginx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/xconnect-nginx:${{ github.sha }}
          
          cache-from: type=gha  
          cache-to: type=gha,mode=max


      - name: Share compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_IP}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/xconnect/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_IP}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true  
          script: |
            set -e
            cd /home/ubuntu/xconnect
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -af
